[build-system]
requires = [
  "setuptools>=77.0.3",
  "setuptools-scm[toml]>=8.0",
  "pybind11>=2.10",
]
build-backend = "setuptools.build_meta"

[project]
name = "riptide-ffa"
authors = [{name = "Vincent Morello", email = "vmorello@gmail.com"}]
description = "Pulsar searching with the Fast Folding Algorithm (FFA)"
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE"]
maintainers = [{name = "Vincent Morello", email = "vmorello@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: C++",
  "Operating System :: Unix",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Scientific/Engineering :: Astronomy",
]

dependencies = [
  "astropy>=5.0",
  "matplotlib>=3.6",
  "numpy>=1.23",
  "pandas>=1.5",
  "pyyaml>=6.0",
  "schema>=0.7.5",
  "threadpoolctl>=3.1",
]

[project.optional-dependencies]
docs = [
  "sphinx>=7.4,<8; python_version < '3.11'",
  "sphinx>=8.2,<9; python_version >= '3.11'",
  "sphinx-rtd-theme>=3,<4",
]
dev = [
  "build>=1.0",
  "pytest>=7.0",
  "pytest-cov>=4.0",
  "twine>=4.0",
]

[project.scripts]
rffa = "riptide.pipeline.pipeline:main"
rseek = "riptide.apps.rseek:main"

[project.urls]
Homepage = "https://github.com/v-morello/riptide"
Documentation = "https://riptide-ffa.readthedocs.io"
Repository = "https://github.com/v-morello/riptide"
Issues = "https://github.com/v-morello/riptide/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/riptide/_version.py"
write_to_source = true

[tool.pytest]
addopts = ["-vv"]

[tool.coverage.run]
branch = true
parallel = true
concurrency = ["multiprocessing"]
omit = ["src/riptide/_version.py"]

[tool.coverage.report]
exclude_lines = [
  "if __name__ == .__main__.:",
  "def main",
]
